---
name: GitHub App Token Generator for Actions
author: Sam McLeod
description: Run a GitHub Action as a GitHub App Installation instead of using secrets.GITHUB_TOKEN or a personal access token.

inputs:
  application_private_key:
    description: GitHub Application Private Key value.
    required: true

  application_id:
    description: GitHub Application ID value.
    required: true

  application_installation_id:
    description: GitHub Install Application ID value.
    required: false

  permissions:
    description: "The permissions to request e.g. issues:read,secrets:write,packages:read. Defaults to all available permissions"
    required: false

  org:
    description: The GitHub Organisation to get the application installation for, if not specified will use the current repository instead. This is not normally needed as the workflow will be running in the context of a repository / org.
    required: false

  owner:
    description: The GitHub Owner to get the application installation for, if not specified will use the current repository instead. This is not normally needed as the workflow will be running in the context of a repository / org.
    required: false

  repo:
    description: The GitHub Repository to get the application installation for, if not specified will use the current repository instead (owner must also be specified). This is not normally needed as the workflow will be running in the context of a repository / org.
    required: false

  github_api_base_url:
    description: The GitHub API base URL to use, no needed it working within the same GitHub instance as the workflow as it will get picked up from the environment. This not usually needed and is mainly for testing purposes.
    required: false

  token_lifetime:
    description: The lifetime of the token in seconds, defaults to 600 (10 minutes).
    required: false

  debug:
    description: Enable debug logging.
    required: false

outputs:
  token:
    description: A valid token representing the Application that can be used to access what the Application has been scoped to access.

  expires_at:
    description: The date and time when the token will expire (UTC).

  permissions_requested:
    description: The permissions that were requested for the token.

  permissions_granted:
    description: The permissions that were granted for the token.

runs:
  using: node20
  main: dist/index.js

branding:
  icon: lock
  color: green
