# Tests this action success by the application already being installed on the repository

name: Test Success - repository - installed - limited permissions

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

# One build per branch, cancel out of date builds only on pull requests
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test-installed-limited:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use action
        id: use_action
        uses: ./
        with:
          application_id: ${{ secrets.GHA_APPLICATION_ID }}
          application_private_key: ${{ secrets.GHA_APPLICATION_PRIVATE_KEY }}
          permissions: "contents:read,actions:read"

      - name: Use token to read details
        uses: actions/github-script@f05a81df23035049204b043b50c3322045ce7eb3 # tag=v3 #TODO: Update to v6
        with:
          github-token: ${{ steps.use_action.outputs.token }}
          script: |
            const repo = await github.repos.get(context.repo);
            console.log(JSON.stringify(repo, null, 2));

      - name: Use token to checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ steps.use_action.outputs.token }}
          repository: sammcj/demo-gha-install-token
